### ISSUE TITLE
python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [trevorhobenshield/proton-api-client#1]
Received this error when I tried `pip install proton-api-client`:

```
Collecting proton-api-client
  Using cached proton_api_client-0.0.7-py3-none-any.whl (23 kB)
Collecting bcrypt
  Using cached bcrypt-4.0.1-cp36-abi3-win_amd64.whl (152 kB)
Collecting python-gnupg
  Using cached python_gnupg-0.5.0-py2.py3-none-any.whl (18 kB)
Collecting pyopenssl
  Using cached pyOpenSSL-23.2.0-py3-none-any.whl (59 kB)
Collecting selectolax
  Using cached selectolax-0.3.14-cp311-cp311-win_amd64.whl (2.0 MB)
Requirement already satisfied: orjson in c:\users\saki\appdata\local\programs\python\python311\lib\site-packages (from proton-api-client) (3.9.1)
Requirement already satisfied: httpx in c:\users\saki\appdata\local\programs\python\python311\lib\site-packages (from proton-api-client) (0.24.1)
Requirement already satisfied: tqdm in c:\users\saki\appdata\local\programs\python\python311\lib\site-packages (from proton-api-client) (4.65.0)
Collecting uvloop
  Using cached uvloop-0.17.0.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Saki\AppData\Local\Temp\pip-install-lmtmd4vp\uvloop_5f7afc69bafc46219b04f0bd50e588d3\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by trevorhobenshield** [comment]
Forgot to update package on PyPI, should be fixed now for Windows users.

**Comment by SakiSakiSakiSakiSaki** [comment]
> Forgot to update package on PyPI, should be fixed now for Windows users.

Taking for updating this, however I think the latest release introduced a bug:

`from proton.client import ProtonMail` will result in the following exception:
```
Exception has occurred: ImportError
Unable to load required functions from SSL dlls
```

The following prints in the terminal:
```
Could not find module 'libeay32.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Could not find module 'libssl32.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Could not find module 'ssleay32.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
